import {defineArrayMember, defineField, defineType} from 'sanity'

export const homePage = defineType({
  name: 'homePage',
  title: 'Homepage',
  type: 'document',
  groups: [
    {name: 'hero', title: 'Hero', default: true},
    {name: 'trust', title: 'Clients and trust'},
    {name: 'services', title: 'Service order'},
    {name: 'seo', title: 'Search and sharing'},
    {name: 'about', title: 'Introduction'},
    {name: 'questions', title: 'FAQs'},
    {name: 'quotes', title: 'Testimonials'},
  ],
  fields: [
    defineField({name: 'heroImage', title: 'Hero artwork override', type: 'accessibleImage', group: 'hero', description: 'Optional transparent portrait artwork. Leave empty to use the supplied Figma statue.'}),
    defineField({name: 'introHeading', title: 'Introduction heading', type: 'string', group: 'about', initialValue: 'Good design gets noticed. Great design gets results.'}),
    defineField({name: 'introBody', title: 'Introduction body', type: 'text', rows: 4, group: 'about', initialValue: 'We bring strategy, identity and experience together to build brands that move people. From the first question to the final detail, we make every decision count.'}),
    defineField({name: 'faqHeading', title: 'FAQ heading', type: 'string', group: 'questions', initialValue: 'Good questions. Straight answers.'}),
    defineField({name: 'faqs', title: 'Frequently asked questions', type: 'array', group: 'questions', description: 'Drag to reorder. Remove every item to hide this section.', of: [defineArrayMember({name: 'faq', type: 'object', fields: [defineField({name: 'question', type: 'string', validation: Rule => Rule.required()}), defineField({name: 'answer', type: 'text', rows: 4, validation: Rule => Rule.required()})], preview: {select: {title: 'question'}}})]}),
    defineField({name: 'testimonials', title: 'Client testimonials', type: 'array', group: 'quotes', description: 'Publish approved, real client quotes. The section stays hidden until a testimonial is added. Drag to reorder.', of: [defineArrayMember({name: 'testimonial', type: 'object', fields: [defineField({name: 'quote', type: 'text', validation: Rule => Rule.required()}), defineField({name: 'name', title: 'Person name', type: 'string', validation: Rule => Rule.required()}), defineField({name: 'role', title: 'Role and company', type: 'string', validation: Rule => Rule.required()}), defineField({name: 'image', title: 'Portrait', type: 'accessibleImage'})], preview: {select: {title: 'name', subtitle: 'role', media: 'image'}}})]}),
    defineField({
      name: 'headlineTop',
      title: 'Headline — first line',
      type: 'string',
      group: 'hero',
      description:
        'The large orange line above the statue. Short copy fits the supplied design best.',
      initialValue: 'BOLD DESIGN',
      validation: (Rule) => [
        Rule.required(),
        Rule.max(18).warning('Longer copy may need a design review.'),
      ],
    }),
    defineField({
      name: 'headlineMiddle',
      title: 'Headline — middle word',
      type: 'string',
      group: 'hero',
      initialValue: 'THAT',
      validation: (Rule) => [
        Rule.required(),
        Rule.max(10).warning('Keep this short to fit beside the statue.'),
      ],
    }),
    defineField({
      name: 'headlineBottom',
      title: 'Headline — last line',
      type: 'string',
      group: 'hero',
      initialValue: 'PERFORMS',
      validation: (Rule) => [
        Rule.required(),
        Rule.max(14).warning('Longer copy may need a design review.'),
      ],
    }),
    defineField({
      name: 'disciplines',
      title: 'Disciplines',
      type: 'array',
      group: 'hero',
      description: 'The list beside the statue. Drag items to change their order.',
      of: [defineArrayMember({type: 'string'})],
      initialValue: ['IDENTITY', 'EXPERIENCE', 'MOTION'],
      validation: (Rule) => Rule.required().min(1).max(4),
    }),
    defineField({
      name: 'strategyStatement',
      title: 'Left statement',
      type: 'string',
      group: 'hero',
      initialValue: 'STRATEGY IS CHEAPER',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'comfortStatement',
      title: 'Right statement',
      type: 'string',
      group: 'hero',
      initialValue: 'COMFORTABLE IS EXPENSIVE',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'contactLink',
      title: 'Header contact link',
      type: 'ctaLink',
      group: 'hero',
      initialValue: {label: 'CONTACT US', href: 'mailto:hello@upthrust.agency'},
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'trustStatistic',
      title: 'Trust statistic',
      type: 'string',
      group: 'trust',
      initialValue: '100+',
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'trustDescription',
      title: 'Trust description',
      type: 'text',
      rows: 2,
      group: 'trust',
      initialValue: "Brands trusted us to define how they're seen.",
      validation: (Rule) => Rule.required(),
    }),
    defineField({
      name: 'clientLogos',
      title: 'Client logos',
      type: 'array',
      group: 'trust',
      description: 'Upload the supplied logo assets. Drag rows to change their order.',
      of: [
        defineArrayMember({
          name: 'clientLogo',
          title: 'Client logo',
          type: 'object',
          fields: [
            defineField({
              name: 'name',
              title: 'Brand name',
              type: 'string',
              validation: (Rule) => Rule.required(),
            }),
            defineField({
              name: 'image',
              title: 'Logo file',
              type: 'accessibleImage',
              validation: (Rule) => Rule.required().warning('Add the original logo export before launch.'),
            }),
          ],
          preview: {select: {title: 'name', media: 'image'}},
        }),
      ],
      validation: (Rule) => Rule.min(1).warning('Add the client logo exports before launch.'),
    }),
    defineField({
      name: 'services',
      title: 'Services displayed on the page',
      type: 'array',
      group: 'services',
      description: 'Choose services and drag them into the order shown in the design.',
      of: [defineArrayMember({type: 'reference', to: [{type: 'service'}]})],
      validation: (Rule) => Rule.required().min(1).max(8).unique(),
    }),
    defineField({
      name: 'seo',
      title: 'Search and sharing',
      type: 'seo',
      group: 'seo',
      validation: (Rule) => Rule.required(),
    }),
  ],
  preview: {
    prepare: () => ({title: 'Homepage', subtitle: 'Hero, client logos, service order and SEO'}),
  },
})
